config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'accounts#index', as: :authenticated_root
  end
  root to: redirect('/login')
  resources :accounts
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout'
  }
  resources :categories
  resources :tags
  resources :transaction_templates
  resources :transactions
end

app/models/transaction_template.rb
class TransactionTemplate < ApplicationRecord
  belongs_to :from_account, class_name: 'Account', optional: true
  belongs_to :to_account, class_name: 'Account', optional: true
  belongs_to :category, optional: true

  monetize :amount_subunit, as: 'amount',
                            with_model_currency: :currency,
                            allow_nil: true

  validates :template_name, presence: true

  enum tx_type: [:expense, :income, :transfer]

  def new_transaction
    Transaction.new(attributes.except('tx_type', 'created_at', 'updated_at', 'template_name'))
  end
end

app/controllers/transaction_templates_controller.rb
class TransactionTemplatesController < ApplicationController
  before_action :set_transaction_template, only: [:show, :edit, :update, :destroy]

  # GET /transaction_templates
  # GET /transaction_templates.json
  def index
    @templates = TransactionTemplate.all
  end

  # GET /transaction_templates/1
  # GET /transaction_templates/1.json
  def show
  end

  # GET /transaction_templates/new
  def new
    @template = TransactionTemplate.new
    @template.tx_type = params[:type]
    respond_modal(:new_template_modal, 'form', "Add #{@template.tx_type} template", @template)
  end

  # GET /transaction_templates/1/edit
  def edit
  end

  # POST /transaction_templates
  # POST /transaction_templates.json
  def create
    @template = TransactionTemplate.new(transaction_template_params)
    if @template.save
      respond_modal_redirect :transaction_templates
    else
      respond_modal(
        :new_template_modal,
        'form',
        "Add #{@template.tx_type} template",
        @template
      )
    end
  end

  # PATCH/PUT /transaction_templates/1
  # PATCH/PUT /transaction_templates/1.json
  def update
    respond_to do |format|
      if @template.update(transaction_template_params)
        format.html { redirect_to @template, notice: 'Transaction template was successfully updated.' }
        format.json { render :show, status: :ok, location: @template }
      else
        format.html { render :edit }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transaction_templates/1
  # DELETE /transaction_templates/1.json
  def destroy
    @template.destroy
    respond_to do |format|
      format.html { redirect_to transaction_templates_url, notice: 'Transaction template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction_template
      @template = TransactionTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_template_params
      params.require(:transaction_template).permit(:tx_type, :template_name, :from_account_id, :to_account_id, :amount, :currency, :name, :description, :tag_list, :category_id)
    end
end

app/helpers/transaction_templates_helper.rb
module TransactionTemplatesHelper
end

app/views/transaction_templates/_form.html.erb
<%= f.text_field :template_name %>
<% if @template.tx_type.to_s != 'income' %>
  <%= f.collection_select :from_account_id, Account.all, :id, :name, {include_blank: true}, {} %>
<% end %>
<% if @template.tx_type.to_s != 'expense' %>
  <%= f.collection_select :to_account_id, Account.all, :id, :name, {include_blank: true}, {} %>
<% end %>
<%= f.text_field :amount %>
<%= f.select :currency, Account.all.collect(&:currency).uniq, selected: params[:currency] %>
<%= f.text_field :name %>
<%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: true}, {} %>
<%= f.text_field :tag_list, id: 'transaction_tags' %>
<script>
  var engine = new Bloodhound({
    local: [
      <% Tag.all.each do |tag| %>
        {value: "<%= tag.name %>"},
      <% end %>
    ],
    datumTokenizer: function(d) {
      return Bloodhound.tokenizers.whitespace(d.value);
    },
    queryTokenizer: Bloodhound.tokenizers.whitespace,
  });

engine.initialize();

$('#transaction_tags').tokenfield({
  'delimiter': ' ',
  typeahead: [null, {
    source: engine.ttAdapter(),
  }]
});
</script>
<%= f.text_area :description %>

<%= f.hidden_field :tx_type %>

app/views/transaction_templates/edit.html.erb
<h1>Editing Transaction Template</h1>

<%= render 'form', transaction_template: @transaction_template %>

<%= link_to 'Show', @transaction_template %> |
<%= link_to 'Back', transaction_templates_path %>

app/views/transaction_templates/index.html.erb
<h1>Transaction templates</h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Template list</h3>
  </div>
  <div class="panel-body">
    <%= link_to({controller: :transaction_templates, action: :new, remote: true, type: 'expense'}, {class: 'btn btn-default'}) do %>
      <span class="pficon pficon-add-circle-o"></span>
      New expense template
    <% end %>
    <%= link_to({controller: :transaction_templates, action: :new, remote: true, type: 'income'}, {class: 'btn btn-default'}) do %>
      <span class="pficon pficon-add-circle-o"></span>
      New income template
    <% end %>
    <%= link_to({controller: :transaction_templates, action: :new, remote: true, type: 'transfer'}, {class: 'btn btn-default'}) do %>
      <span class="pficon pficon-add-circle-o"></span>
      New transfer template
    <% end %>
    <div class="list-group list-view-pf list-view-pf-view">
      <% @templates.each do |template| %>
        <div class="list-group-item">
          <div class="list-view-pf-actions compact-list">
            <%= link_to({controller: :transactions, action: :new, template: template.template_name, remote: true}, {class: 'btn btn-default'}) do %>
              Use
            <% end %>
            <%= link_to 'Delete', template, method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure?' } %>
          </div>
          <div class="list-view-pf-main-info compact-list">
            <div class="list-view-pf-body">
              <div class="list-view-pf-description">
                <div class="list-group-item-heading">
                  <%= template.template_name %>
                </div>
                <div class="list-group-item-text">
                  <%= template.tx_type %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/transaction_templates/new.html.erb
<h1>New Transaction Template</h1>

<%= render 'form', transaction_template: @transaction_template %>

<%= link_to 'Back', transaction_templates_path %>

app/views/transaction_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tx type:</strong>
  <%= @transaction_template.tx_type %>
</p>

<p>
  <strong>Template name:</strong>
  <%= @transaction_template.template_name %>
</p>

<p>
  <strong>From account:</strong>
  <%= @transaction_template.from_account %>
</p>

<p>
  <strong>To account:</strong>
  <%= @transaction_template.to_account %>
</p>

<p>
  <strong>Amount subunit:</strong>
  <%= @transaction_template.amount_subunit %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @transaction_template.currency %>
</p>

<p>
  <strong>Name:</strong>
  <%= @transaction_template.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction_template.description %>
</p>

<%= link_to 'Edit', edit_transaction_template_path(@transaction_template) %> |
<%= link_to 'Back', transaction_templates_path %>