config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'accounts#index', as: :authenticated_root
  end
  root to: redirect('/login')
  resources :accounts
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout'
  }
  resources :categories
  resources :tags
  resources :transaction_templates
  resources :transactions
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    respond_modal(:new_category_modal, 'form', "Add category", @category)
  end

  # GET /categories/1/edit
  def edit
    respond_modal(:edit_category_modal, 'form', "Edit category", @category)
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    if @category.save
      respond_modal_redirect :categories
    else
      respond_modal(:new_category_modal, 'form', "Add category", @category)
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    if @category.update(category_params)
      respond_modal_redirect :categories
    else
      respond_modal(:edit_category_modal, 'form', "Edit category", @category)
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= f.text_field :name %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Category list</h3>
  </div>
  <div class="panel-body">
    <%= link_to({controller: :categories, action: :new, remote: true}, {class: 'btn btn-default'}) do %>
      <span class="pficon pficon-add-circle-o"></span>
      New category
    <% end %>
    <div class="list-group list-view-pf list-view-pf-view">
      <% @categories.each do |category| %>
        <div class="list-group-item">
          <div class="list-view-pf-actions compact-list">
            <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-default', remote: true %>
            <%= link_to 'Delete', category, method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure?' } %>
          </div>
          <div class="list-view-pf-main-info compact-list">
            <div class="list-view-pf-body">
              <div class="list-view-pf-description">
                <div class="list-group-item-heading">
                  <%= link_to category.name, category %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>