config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: 'accounts#index', as: :authenticated_root
  end
  root to: redirect('/login')
  resources :accounts
  devise_for :users, path: '', path_names: {
    sign_in: 'login', sign_out: 'logout'
  }
  resources :categories
  resources :tags
  resources :transaction_templates
  resources :transactions
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :set_template, only: [:new, :create]
  before_action :set_filter, only: [:index]

  # GET /transactions
  # GET /transactions.json
  def index
    if filter_params
      @transactions = Transaction.all
      apply_condition(
        "category_id = :id",
        id: @filter.category_id
      )
      apply_condition(
        "from_account_id = :id OR to_account_id = :id",
        id: @filter.account
      )
      apply_condition("date >= ?", @filter.from_date)
      apply_condition("date <= ?", @filter.to_date)
      apply_condition(
        "EXISTS (
           SELECT 1
             FROM transactions_tags
               INNER JOIN tags
                 ON tags.id = transactions_tags.tag_id
           WHERE transaction_id = transactions.id
             AND tags.name IN (?)
         )",
        @filter.tags
      )
      @transactions = case @filter.type
                     when 'expense'
                       @transactions.where(to_account_id: nil)
                     when 'income'
                       @transactions.where(from_account_id: nil)
                     when 'transfer'
                       @transactions.where(
                         'from_account_id IS NOT NULL AND to_account_id IS NOT NULL'
                       )
                     else
                       @transactions
                     end
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = @template.new_transaction
    @transaction.from_account_id = params[:from_account] if params[:from_account]
    @transaction.to_account_id = params[:to_account] if params[:to_account]
    @transaction.currency = params[:currency] if params[:currency]
    @transaction.date = Date.today
    respond_modal(:new_transaction_modal, 'form', "Add #{@template.template_name}", @transaction)
  end

  # GET /transactions/1/edit
  def edit
    respond_modal(:update_transaction_modal, 'form', "Edit #{@tx_type}", @transaction)
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      respond_modal_redirect :transactions
    else
      respond_modal(
        :new_transaction_modal,
        'form',
        "Add #{@template.template_name}",
        @transaction
      )
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    if @transaction.update(transaction_params)
      respond_modal_redirect :transactions
    else
      respond_modal(
        :update_transaction_modal,
        'form',
        "Edit #{@tx_type}",
        @transaction
      )
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_transaction
    @transaction = Transaction.find(params[:id])
    @tx_type = @transaction.tx_type
  end

  def set_template
    @template = case params[:template]
                when nil, 'transfer'
                  TransactionTemplate.new(tx_type: :transfer)
                when 'expense'
                  TransactionTemplate.new(tx_type: :expense)
                when 'income'
                  TransactionTemplate.new(tx_type: :income)
                else
                  TransactionTemplate.find_by_template_name(params[:template])
                end
    @template.template_name ||= @template.tx_type.to_s
    @tx_type = @template.tx_type
  end

  def transaction_params
    params.require(:transaction).permit(:from_account_id, :to_account_id, :amount, :currency, :name, :description, :date, :category_id, :tag_list)
  end

  def set_filter
    @filter = Filter.new(filter_params)
    @format = params[:format]
  end

  def filter_params
    if params[:filter]
      params[:filter].permit(:category_id, :from_date, :to_date, :tag_list, :account, :type)
    end
  end

  def apply_condition(expression, *values, **key_values)
    if values.all?(&:present?) and key_values.values.all?(&:present?)
      values << key_values unless key_values.empty?
      @transactions = @transactions.where(expression, *values)
    end
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def transaction_pie_chart(transactions)
    data = transactions.to_a.group_by(&:category).collect do |cat, txs|
      [cat ? cat.name : 'uncategorized',
       txs.sum(&:amount).exchange_to(:CZK).to_f]
    end
    pie_chart(data)
  end
end

app/views/transactions/_filter.html.erb
<%= bootstrap_form_for filter, url: path, method: :get, control_col: 'col-sm-9', label_col: 'col-sm-3' do |f| %>
  <div class="row">
    <div class="col-md-3">
      <%= f.select :type, [:all, :expense, :income, :transfer], {class: 'selectpicker'} %>
    </div>
    <div class="col-md-3">
      <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: true}, {} %>
    </div>
    <div class="col-md-3">
      <%= f.collection_select :account, Account.all, :id, :name,
        {include_blank: 'All accounts'}, {class: 'selectpicker'} %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= f.text_field :tag_list, id: 'transaction_tags' %>
      <script>
        var engine = new Bloodhound({
          local: [
            <% Tag.all.each do |tag| %>
              {value: "<%= tag.name %>"},
            <% end %>
          ],
          datumTokenizer: function(d) {
            return Bloodhound.tokenizers.whitespace(d.value);
          },
          queryTokenizer: Bloodhound.tokenizers.whitespace,
        });

      engine.initialize();

      $('#transaction_tags').tokenfield({
        'delimiter': ' ',
        typeahead: [null, {
          source: engine.ttAdapter(),
        }]
      });
      </script>
    </div>
    <div class="col-md-3">
      <%= f.datepicker :from_date %>
    </div>
    <div class="col-md-3">
      <%= f.datepicker :to_date %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3">
      <button type="submit" name="format" class="btn btn-default" value="list">Show list</button>
      <button type="submit" name="format" class="btn btn-default" value="graph">Show graph</button>
      <a href="<%= path %>" class="btn btn-default">Clear filter</a>
    </div>
  </div>
<% end %>

app/views/transactions/_form.html.erb
<% if @tx_type.to_s != 'income' %>
  <%= f.collection_select :from_account_id, Account.all, :id, :name, {include_blank: true}, {} %>
<% end %>
<% if @tx_type.to_s != 'expense' %>
  <%= f.collection_select :to_account_id, Account.all, :id, :name, {include_blank: true}, {} %>
<% end %>
<%= f.text_field :amount %>
<%= f.select :currency, Account.all.collect(&:currency).uniq %>
<%= f.text_field :name %>
<%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: true}, {} %>
<%= f.text_field :tag_list, id: 'transaction_tags' %>
<script>
  var engine = new Bloodhound({
    local: [
      <% Tag.all.each do |tag| %>
        {value: "<%= tag.name %>"},
      <% end %>
    ],
    datumTokenizer: function(d) {
      return Bloodhound.tokenizers.whitespace(d.value);
    },
    queryTokenizer: Bloodhound.tokenizers.whitespace,
  });

engine.initialize();

$('#transaction_tags').tokenfield({
  'delimiter': ' ',
  typeahead: [null, {
    source: engine.ttAdapter(),
  }]
});
</script>
<%= f.text_area :description %>
<%= f.datepicker :date %>

<% if defined? @template %>
  <input type="hidden" name="template" value="<%= @template.template_name %>"/>
<% end %>

app/views/transactions/_graph.html.erb
<% income = transactions.select { |tx| tx.tx_type == :income } %>
<% expense = transactions.select { |tx| tx.tx_type == :expense } %>
<div class="row">
  <div class="col-md-6">
    <h3>Income by category</h3>
    <%= transaction_pie_chart(income) %>
  </div>
  <div class="col-md-6">
    <h3>Expenses by category</h3>
    <%= transaction_pie_chart(expense) %>
  </div>
</div>

app/views/transactions/_list.html.erb
<div class="list-group list-view-pf list-view-pf-view">
  <% transactions.each do |tx| %>
    <div class="list-group-item">
      <div class="list-group-item-header">
        <div class="list-view-pf-expand compact-list">
          <span class="fa fa-angle-right"></span>
        </div>

        <div class="list-view-pf-actions compact-list">
          <%= link_to 'Edit', edit_transaction_path(tx), class: 'btn btn-default', remote: true %>
          <%= link_to 'Delete', tx, method: :delete, class: 'btn btn-default', data: { confirm: 'Are you sure?' } %>
        </div>
        <div class="list-view-pf-main-info compact-list">
          <div class="list-view-pf-body row">
            <div class="col-md-2">
              <%= tx.name %>
            </div>
            <div class="col-md-2">
              <% if tx.category %>
                <span class="token-readonly category">
                  <%= tx.category.name %>
                </span>
              <% end %>
            </div>
            <div class="col-md-2">
              <span class="fa fa-money"></span>
              <% if tx.tx_type == :expense %>
                <span class="negative-amount">-<%= tx.amount.format %></span>
              <% elsif tx.tx_type == :income  %>
                <span class="positive-amount">+<%= tx.amount.format %></span>
              <% elsif defined? account and tx.from_account == account %>
                <span class="transfer-amount">-<%= tx.amount.format %></span>
              <% elsif defined? account and tx.to_account == account %>
                <span class="transfer-amount">+<%= tx.amount.format %></span>
              <% else %>
                <span class="transfer-amount"><%= tx.amount.format %></span>
              <% end %>
            </div>
            <div class="col-md-2">
              <span class="fa fa-calendar"></span>
              <%= tx.date %>
            </div>
            <div class="col-md-1">
              <% if tx.from_account and not (defined? account and tx.from_account == account) %> From:&nbsp;<%= link_to tx.from_account.name, tx.from_account %> <% end %>
            </div>
            <div class="col-md-1">
              <% if tx.to_account and not (defined? account and tx.to_account == account) %> To:&nbsp;<%= link_to tx.to_account.name, tx.to_account %> <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="list-group-item-container hidden">
        <div class="close">
          <span class="pficon pficon-close"></span>
        </div>
        <div class="row">
          <div class="col-md-12">
            <% tx.tags.each do |tag| %>
              <span class="token-readonly">
                <%= tag.name %>
              </span>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <%= tx.description %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<script>
  $(document).ready(function () {
    // click the list-view heading then expand a row
    $(".list-group-item-header").click(function(event){
      if(!$(event.target).is("button, a, input, .fa-ellipsis-v")){
        $(this).find(".fa-angle-right").toggleClass("fa-angle-down")
          .end().parent().toggleClass("list-view-pf-expand-active")
          .find(".list-group-item-container").toggleClass("hidden");
      } else {
      }
    })

    // click the close button, hide the expand row and remove the active status
    $(".list-group-item-container .close").on("click", function (){
      $(this).parent().addClass("hidden")
        .parent().removeClass("list-view-pf-expand-active")
        .find(".fa-angle-right").removeClass("fa-angle-down");
    })

  });
</script>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Search</h3>
  </div>
  <div class="panel-body">
    <%= render 'filter', filter: @filter, path: transactions_path %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Actions</h3>
  </div>
  <div class="panel-body">
    <%= link_to({controller: :transactions, action: :new, template: :expense, remote: true}, {class: 'btn btn-default'}) do %>
      <span class="pficon pficon-add-circle-o"></span>
      Add expense
    <% end %>
    <%= link_to({controller: :transactions, action: :new, template: :income, remote: true}, {class: 'btn btn-default'}) do %>
      <span class="pficon pficon-add-circle-o"></span>
      Add income
    <% end %>
    <%= link_to({controller: :transactions, action: :new, template: :transfer, remote: true}, {class: 'btn btn-default'}) do %>
      <span class="pficon pficon-add-circle-o"></span>
      Add transfer
    <% end %>
  </div>
</div>

<% if @transactions %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Transactions</h3>
    </div>
    <% if @format == 'list' %>
      <%= render 'list', transactions: @transactions %>
    <% elsif @format == 'graph' %>
      <%= render 'graph', transactions: @transactions %>
    <% end %>
  </div>
</div>
<% end %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/search.html.erb
<h1>Search results</h1>

<%= render 'list', transactions: @transactions %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From account:</strong>
  <%= @transaction.from_account.name %>
</p>

<p>
  <strong>To account:</strong>
  <%= @transaction.to_account.name %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Name:</strong>
  <%= @transaction.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>